.PHONY: clean All

All:
	@echo "----------Building project:[ pyq - Debug ]----------"
	@cd "pyq" && "$(MAKE)" -f  "pyq.mk"
clean:
	@echo "----------Cleaning project:[ pyq - Debug ]----------"
	@cd "pyq" && "$(MAKE)" -f  "pyq.mk" clean
